service: mac-serverless-lambda-retry-sqs
frameworkVersion: "3"

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs18.x

functions:
  trigger:
    handler: index.trigger
    events:
      - sqs:
          arn:
            Fn::Join:
              - ":"
              - - arn
                - aws
                - sqs
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - my-data-queue

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: my-data-queue
